---
- name: Provision compute instances and storage volumes
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Create storage volumes
      os_volume:
        auth: "{{ os_auth }}"
        display_name: magicDemo-storage-{{ item }}
        display_description: persistent magicDemo storage volume
        availability_zone: "{{ os_availability_zone }}"
        size: "{{ magicDemo_storage_volume_size }}"
        wait: no
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1

    - name: Wait for all storage volumes to be ready
      os_volume:
        auth: "{{ os_auth }}"
        display_name: magicDemo-storage-{{ item }}
        display_description: persistent magicDemo storage volume
        availability_zone: "{{ os_availability_zone }}"
        size: "{{ magicDemo_storage_volume_size }}"
        wait: yes
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1
      register: magicDemo_storage_volumes

    - name: Launch magicDemo compute instances
      os_server:
        auth: "{{ os_auth }}"
        name: magicDemo-{{ item }}
        auto_ip: no
        image: "{{ os_image }}"
        flavor: "{{ os_flavor }}"
        key_name: "{{ os_key_pair }}"
        nics:
          - net-name: "{{ os_network_name }}"
        volumes:
          - magicDemo-storage-{{ item }}
        security_groups:
          - ssh
          - magicDemo
        wait: no
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1

    - name: Wait a little while for instances to get out of BUILD state
      pause:
        seconds: 20

    - name: Wait for all compute instances to be ready
      os_server:
        auth: "{{ os_auth }}"
        name: magicDemo-{{ item }}
        auto_ip: no
        image: "{{ os_image }}"
        flavor: "{{ os_flavor }}"
        key_name: "{{ os_key_pair }}"
        nics:
          - net-name: "{{ os_network_name }}"
        volumes:
          - magicDemo-storage-{{ item }}
        security_groups:
          - ssh
          - magicDemo
        wait: yes
        state: present
      with_sequence: start=0 end={{ osd_count - 1 }} stride=1
      register: magicDemo_compute_instances

    - name: Add all provisioned instances to inventory
      add_host:
        name: "{{ item.1.openstack.name }}"
        groups: magicDemo
        ansible_host: "{{ item.1.openstack.private_v4 }}"
      changed_when: false
      with_indexed_items: magicDemo_compute_instances.results
